sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

# cloud.gov database compatibility
<%
  begin
    services = JSON.parse(ENV['VCAP_SERVICES'])
    credentials = services['aws-rds'].first['credentials']
  rescue
    credentials = {}
  end
%>

production:
  adapter: postgresql
  encoding: unicode
<% if !credentials.empty? %>
  database: <%= credentials['db_name'] || '' %>
  username: <%= credentials['username'] || '' %>
  host: <%= credentials['host'] || 'localhost' %>
  password: <%= credentials['password'] || '' %>
  port: <%= credentials['port'] || '3306' %>
<% else %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
<% end %>

