
development:
  acs_url: http://localhost:5000/auth/saml/callback
  idp_cert_fingerprint: '8B:D5:C2:E8:9A:2B:CE:B7:4B:95:50:BA:16:79:05:27:17:D1:D3:67'
  idp_slo_url: http://localhost:3000/api/saml/logout
  idp_sso_url: http://localhost:3000/api/saml/auth
  login_url: http://localhost:3000/account
  saml_issuer: urn:gov:gsa:SAML:2.0.profiles:sp:naas-local
  secret_key_base: rake secret
  twilio_auth_token: 4cffffffffffffffffff
  twilio_number: 12025555555
  twilio_sid: ACXXXXXXXXXXXXXXXXXXX

test:
  acs_url: http://localhost:5000/auth/saml/callback
  idp_cert_fingerprint: '8B:D5:C2:E8:9A:2B:CE:B7:4B:95:50:BA:16:79:05:27:17:D1:D3:67'
  idp_slo_url: http://localhost:3000/api/saml/logout
  idp_sso_url: http://localhost:3000/api/saml/auth
  login_url: https://login-demo.app.cloud.gov/account
  saml_issuer: urn:gov:gsa:SAML:2.0.profiles:sp:naas-local
  secret_key_base: rake secret
  twilio_auth_token: 4cffffffffffffffffff
  twilio_number: 12025555555
  twilio_sid: ACXXXXXXXXXXXXXXXXXXX

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  acs_url: <%= ENV['SAML_ACS_URL'] %>
  idp_cert_fingerprint: <%= ENV['IDP_CERT_FINGERPRINT'] %>
  idp_slo_url: <% ENV['SAML_IDP_SLO_URL'] %>
  idp_sso_url: <%= ENV['SAML_IDP_SSO_URL'] %>
  login_url: <%= ENV['LOGIN_URL'] %>
  saml_issuer: <%= ENV['SAML_ISSUER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>
  twilio_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>

