# Application configuration and secrets. Any changes to this file
# requires the server to restart.
development:
  secret_key_base: 11d934e1b5a0498e745bedfd91513eebc9d59b10c1fdd3be2af1926ea4fab244120319bbfebe3701329c0ddda22bb358d9a49d015d0c87a620827651cf335c08
  twilio_auth_token: 4cffffffffffffffffff
  twilio_number: 12025555555
  twilio_sid: ACXXXXXXXXXXXXXXXXXXX

test:
  secret_key_base: bc6bb69af407f2835a516741b8d9ab5fba764c9aee5976094decca1767b7fc75a13461f2c610ed21fc391401d8171dec23973face1b75a04f58bcb937ab367bc
  twilio_auth_token: 4cffffffffffffffffff
  twilio_number: 12025555555
  twilio_sid: ACXXXXXXXXXXXXXXXXXXX

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>
  twilio_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
